In [2]:
import numpy as np

## Write a Numpy program to compute the multiplication of two given matrixes

In [37]:
def mat_mult(x, y):
  if len(x.shape) != 1 and len(y.shape) != 1:
    if x.shape[1] == y.shape[1]:
      return x * y
  elif len(x.shape) == 1 and len(y.shape) == 1:
    if x.shape[0] == y.shape[0]:
      return x * y
  elif len(x.shape) == 1:
    if x.shape[0] == y.shape[1]:
      return x * y
  elif len(y.shape) == 1:
    if x.shape[1] == y.shape[0]:
      return x * y

In [38]:
a = np.array([[1,2,3],[5,6,7]])
b = np.array([[4,5,6],[7,7,7]])

mat_mult(a, b)

array([[ 4, 10, 18],
       [35, 42, 49]])

## Write a NumPy program to compute the determinant of a given square array

In [39]:
def mat_det(x):
  if len(x.shape) != 1:     # not a vector
    return np.linalg.det()

In [57]:
a = np.arange(5,90,10,dtype=np.float64).reshape(3,3)
mat_det(a)

8.526512829121214e-12

## Write a NumPy program to compute the cross product of two given vectors

In [61]:
def vec_cross(x, y):
  if len(x.shape) == 1 and len(y.shape) == 1:
    if x.shape[0] == y.shape[0]:
      return x * y

In [62]:
a = np.array([1,2,3,4,5])
b = np.array([1,2,3,4,5])

vec_cross(a, b)

array([ 1,  4,  9, 16, 25])

## Write a NumPy program to compute the condition number of a given matrix

In [68]:
def mat_cond(x):
  if len(x.shape) != 1:
    return np.linalg.cond(x)

In [70]:
a = np.arange(1,10,1).reshape(3,3)
mat_cond(a)

3.813147060626918e+16

## Write a NumPy program to compute the inverse of a given matrix

In [83]:
def mat_inv(x):
  if len(x.shape) != 1:
    if x.shape[0] == x.shape[1]:
      return np.linalg.inv(x)

In [84]:
a = np.array([[2,1,4,2],
              [1,2,4,7],
              [2,5,6,9],
              [2,6,3,11]])

mat_inv(a)

array([[ 0.75257732, -0.07216495, -0.69072165,  0.4742268 ],
       [-0.19587629, -0.51546392,  0.49484536, -0.04123711],
       [-0.07216495,  0.02061856,  0.34020619, -0.27835052],
       [-0.01030928,  0.28865979, -0.2371134 ,  0.10309278]])